// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASPCore5Demo_1.Model
{
    public partial class Department_DeleteResult
    {
    }
}
